import { useState, useEffect } from "react";
import { X, Mail, RefreshCw, BookmarkPlus, Send, Sparkles, CheckCircle2, AlertCircle } from "lucide-react";

export default function ColdEmailPopupModal({ isOpen, onClose, emailDraft, onRedraft, onSaveDraft }) {
  const [subject, setSubject] = useState(emailDraft?.subject || "");
  const [body, setBody] = useState(emailDraft?.body || "");
  const [hrName, setHrName] = useState(emailDraft?.hr_recruiter_name || "Talent Acquisition Team");
  const [hrEmail, setHrEmail] = useState(emailDraft?.hr_recruiter_email || "careers@company.com");
  const [isRedrafting, setIsRedrafting] = useState(false);
  const [isSavingDraft, setIsSavingDraft] = useState(false);
  const [draftSavedSuccess, setDraftSavedSuccess] = useState(false);

  useEffect(() => {
    if (emailDraft) {
      setSubject(emailDraft.subject || "");
      setBody(emailDraft.body || "");
      setHrName(emailDraft.hr_recruiter_name || "Talent Acquisition Team");
      setHrEmail(emailDraft.hr_recruiter_email || "careers@company.com");
    }
  }, [emailDraft]);

  if (!isOpen || !emailDraft) return null;

  const handleRedraftClick = async () => {
    setIsRedrafting(true);
    try {
      const freshDraft = await onRedraft(emailDraft.company_name, emailDraft.position, emailDraft.location, true, hrName, hrEmail);
      if (freshDraft) {
        setSubject(freshDraft.subject || subject);
        setBody(freshDraft.body || body);
      }
    } catch (err) {
      alert("Failed to re-draft email: " + err.message);
    } finally {
      setIsRedrafting(false);
    }
  };

  const handleSaveDraftClick = async () => {
    setIsSavingDraft(true);
    try {
      await onSaveDraft({
        company: emailDraft.company_name,
        role: emailDraft.position,
        subject,
        body,
        hr_name: hrName,
        hr_email: hrEmail,
      });
      setDraftSavedSuccess(true);
      setTimeout(() => setDraftSavedSuccess(false), 3000);
    } catch (err) {
      alert("Failed to save draft in Gmail: " + err.message);
    } finally {
      setIsSavingDraft(false);
    }
  };

  const handleSendBlankClick = () => {
    alert("Send functionality is currently unlinked (as configured).");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md">
      <div className="relative max-w-2xl w-full cyber-panel p-6 rounded-2xl border border-purple-500/40 shadow-2xl text-left max-h-[90vh] overflow-y-auto">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1 rounded-lg text-slate-400 hover:text-slate-100 hover:bg-slate-800 transition-colors"
        >
          <X className="h-5 w-5" />
        </button>

        <div className="flex items-center gap-3 mb-4 pb-3 border-b border-slate-800">
          <div className="h-10 w-10 rounded-xl bg-purple-500/20 text-purple-400 border border-purple-500/30 flex items-center justify-center font-black">
            <Mail className="h-5 w-5" />
          </div>
          <div>
            <h3 className="text-sm font-black uppercase text-slate-100 tracking-wide flex items-center gap-2">
              <span>AI COLD EMAIL DRAFT STUDIO</span>
              <span className="text-[10px] font-mono text-purple-400 bg-purple-500/10 border border-purple-500/30 px-2 py-0.5 rounded-full">
                [{emailDraft.company_name} // {emailDraft.position}]
              </span>
            </h3>
            <p className="text-[10px] font-mono text-slate-400 mt-0.5">
              Personalized cold outreach generated by Gemini AI Agent
            </p>
          </div>
        </div>

        <div className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="text-[10px] font-mono text-slate-400 block mb-1 font-bold">
                RECRUITER NAME
              </label>
              <input
                type="text"
                value={hrName}
                onChange={(e) => setHrName(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs font-mono text-slate-200 focus:outline-none focus:border-purple-500/50"
              />
            </div>

            <div>
              <label className="text-[10px] font-mono text-slate-400 block mb-1 font-bold">
                RECRUITER EMAIL
              </label>
              <input
                type="email"
                value={hrEmail}
                onChange={(e) => setHrEmail(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs font-mono text-purple-400 focus:outline-none focus:border-purple-500/50"
              />
            </div>
          </div>

          <div>
            <label className="text-[10px] font-mono text-slate-400 block mb-1 font-bold">
              EMAIL SUBJECT
            </label>
            <input
              type="text"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2 text-xs font-mono text-lime-400 focus:outline-none focus:border-purple-500/50"
            />
          </div>

          <div>
            <label className="text-[10px] font-mono text-slate-400 block mb-1 font-bold">
              GENERATED COLD EMAIL BODY
            </label>
            <textarea
              rows={8}
              value={body}
              onChange={(e) => setBody(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3.5 text-xs font-mono text-slate-200 focus:outline-none focus:border-purple-500/50 leading-relaxed"
            />
          </div>

          {draftSavedSuccess && (
            <div className="p-3 rounded-xl bg-purple-500/10 border border-purple-500/30 text-purple-400 font-mono text-xs text-center flex items-center justify-center gap-2 font-bold">
              <CheckCircle2 className="h-4 w-4" />
              <span>[DRAFT_SAVED_IN_GMAIL_INBOX_SUCCESSFULLY]</span>
            </div>
          )}

          {/* 3 ACTION BUTTONS */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 pt-3 border-t border-slate-800">
            {/* Button 1: Re-draft Email */}
            <button
              onClick={handleRedraftClick}
              disabled={isRedrafting}
              className="py-2.5 px-3 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-200 font-mono font-bold text-xs border border-slate-800 flex items-center justify-center gap-1.5 transition-all"
            >
              <RefreshCw className={`h-3.5 w-3.5 text-purple-400 ${isRedrafting ? "animate-spin" : ""}`} />
              <span>{isRedrafting ? "RE-DRAFTING..." : "🔄 Re-draft Email"}</span>
            </button>

            {/* Button 2: Save as Draft in Gmail */}
            <button
              onClick={handleSaveDraftClick}
              disabled={isSavingDraft}
              className="py-2.5 px-3 rounded-xl bg-purple-600/20 hover:bg-purple-600/30 text-purple-300 font-mono font-bold text-xs border border-purple-500/40 flex items-center justify-center gap-1.5 transition-all"
            >
              <BookmarkPlus className="h-3.5 w-3.5 text-purple-400" />
              <span>{isSavingDraft ? "SAVING DRAFT..." : "💾 Save as Draft in Gmail"}</span>
            </button>

            {/* Button 3: Send Email (Functionality Blank For Now) */}
            <button
              onClick={handleSendBlankClick}
              className="py-2.5 px-3 rounded-xl bg-lime-400/20 hover:bg-lime-400/30 text-lime-400 font-mono font-bold text-xs border border-lime-400/30 flex items-center justify-center gap-1.5 transition-all"
            >
              <Send className="h-3.5 w-3.5 text-lime-400" />
              <span>🚀 Send Email</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
